version: "3.3"
services:
  privat_bank_api:
    build: .
    restart: always
    ports:
    - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl localhost:8000/healthcheck/ | grep OK"]
      interval: 10s
      timeout: 1s
      retries: 2
