"""empty message

Revision ID: 0351b1f078f6
Revises: 9366be3ba6bc
Create Date: 2020-01-04 00:08:39.380028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0351b1f078f6'
down_revision = '9366be3ba6bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops_products', sa.Column('amount', sa.Integer(), nullable=False))
    op.add_column('shops_products', sa.Column('delivery_date', sa.DateTime(), nullable=False))
    op.add_column('shops_products', sa.Column('id', sa.Integer(), autoincrement=True, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops_products', 'id')
    op.drop_column('shops_products', 'delivery_date')
    op.drop_column('shops_products', 'amount')
    # ### end Alembic commands ###
