"""empty message

Revision ID: 2c33cb228803
Revises: a1452c304554
Create Date: 2019-12-15 23:44:48.848256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c33cb228803'
down_revision = 'a1452c304554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'product_id')
    # ### end Alembic commands ###
