"""empty message

Revision ID: 6aeeb97dd716
Revises: 2c33cb228803
Create Date: 2019-12-15 23:54:25.745174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aeeb97dd716'
down_revision = '2c33cb228803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_product_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'product_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_product_id_fkey', 'users', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
