"""empty message

Revision ID: 827498dea93b
Revises: 4c1c08f5a98b
Create Date: 2019-12-15 10:25:38.947862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '827498dea93b'
down_revision = '4c1c08f5a98b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('city', sa.String(length=60), nullable=False))
    op.add_column('shops', sa.Column('name', sa.String(length=60), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'name')
    op.drop_column('shops', 'city')
    # ### end Alembic commands ###
