"""empty message

Revision ID: 9366be3ba6bc
Revises: a457e3397ca6
Create Date: 2020-01-03 21:38:53.831557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9366be3ba6bc'
down_revision = 'a457e3397ca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('closed_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('orders', sa.Column('is_closed', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('is_processed', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('name', sa.Integer(), nullable=True))
    op.drop_constraint('orders_product_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_user_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['name'], ['id'])
    op.drop_column('orders', 'product_id')
    op.drop_column('orders', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_user_id_fkey', 'orders', 'users', ['user_id'], ['id'])
    op.create_foreign_key('orders_product_id_fkey', 'orders', 'products', ['product_id'], ['id'])
    op.drop_column('orders', 'name')
    op.drop_column('orders', 'is_processed')
    op.drop_column('orders', 'is_closed')
    op.drop_column('orders', 'created_at')
    op.drop_column('orders', 'closed_at')
    # ### end Alembic commands ###
