"""empty message

Revision ID: a1452c304554
Revises: 827498dea93b
Create Date: 2019-12-15 22:14:02.725784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1452c304554'
down_revision = '827498dea93b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category', sa.String(length=50), nullable=False))
    op.add_column('products', sa.Column('description', sa.String(length=1000), nullable=True))
    op.add_column('products', sa.Column('image', sa.String(), nullable=True))
    op.add_column('products', sa.Column('name', sa.String(length=50), nullable=False))
    op.add_column('products', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('products', sa.Column('shop', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'products', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_column('products', 'shop')
    op.drop_column('products', 'price')
    op.drop_column('products', 'name')
    op.drop_column('products', 'image')
    op.drop_column('products', 'description')
    op.drop_column('products', 'category')
    # ### end Alembic commands ###
