"""empty message

Revision ID: a457e3397ca6
Revises: afefdea1144d
Create Date: 2020-01-03 21:19:49.155870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a457e3397ca6'
down_revision = 'afefdea1144d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category', sa.Integer(), nullable=True))
    op.drop_constraint('products_category_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'category', ['category'], ['id'])
    op.drop_column('products', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_category_id_fkey', 'products', 'category', ['category_id'], ['id'])
    op.drop_column('products', 'category')
    # ### end Alembic commands ###
