"""empty message

Revision ID: f0cf1dca4c28
Revises: dc1da4e9b479
Create Date: 2020-01-03 21:12:10.812700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0cf1dca4c28'
down_revision = 'dc1da4e9b479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_foreign_key(None, 'products', 'category', ['category'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
